### ISSUE TITLE
[FEATURE] `wash up` should have a flag to specify a NATS server config

### ISSUE THREAD

**Issue by protochron** [wasmCloud/wasmCloud#1405] opened 2024-01-29 14:56 UTC
### Affected project(s)

- [ ] documentation
- [ ] examples
- [ ] wasmCloud host
- [X] wasmCloud CLI (wash)
- [ ] wasmCloud dashboard UI (washboard)
- [ ] capability providers
- [ ] provider bindgen
- [ ] control interface client
- [ ] other / not sure

### Is your feature request related to a problem? Please describe.

Right now it is impossible to specify a NATS server config since wash does the right thing and creates one for you when you run `wash up`. Normally this is fine, but if you are working with a particular NATS setup or want to set specific values in the NATS server configuration you have no way to do that

### Describe the solution you'd like

A `--nats-config-file` flag (or something like it!) that allows you to provide a custom NATS server config file that `wash` will use to start the NATS server.

**Comment by UtkarshUmre** [comment] 2024-01-30 12:27
@protochron What needs to be done to solve this issue? It would be really helpful if you could give some guidance or point to some beginner-friendly resources

**Comment by brooksmtownsend** [comment] 2024-01-30 14:17
@UtkarshUmre I'm not @protochron, but i can point you in the right direction 😄 

So when you launch wasmCloud development infrastructure with `wash up`, we accept a couple NATS parameters so you can change things like the port to listen on, NATS address, credentials, etc.
```
➜ wash up --help | grep nats
      --nats-credsfile <NATS_CREDSFILE>
      --nats-remote-url <NATS_REMOTE_URL>
      --nats-connect-only
      --nats-version <NATS_VERSION>
          NATS server version to download, e.g. `v2.10.7`. See https://github.com/nats-io/nats-server/releases/ for releases [en
v: NATS_VERSION=] [default: v2.10.7]
      --nats-host <NATS_HOST>
      --nats-port <NATS_PORT>
          NATS server port to connect to. This will be used as the NATS listen port if `--nats-connect-only` isn't set [env: WAS
MCLOUD_NATS_PORT=]
      --nats-websocket-port <NATS_WEBSOCKET_PORT>
      --nats-js-domain <NATS_JS_DOMAIN>
```

Under the hood, we take these parameters and create a NATS config and then write it to the `~/.wash` directory https://github.com/wasmCloud/wasmCloud/blob/main/crates/wash-lib/src/start/nats.rs#L278.

What @protochron is suggesting here is, instead of supplying many different configuration flags, it would be nice to simply supply a flag like `--nats-config ./myconfig` and wash will use that configuration for NATS instead.

**Comment by 7h3-3mp7y-m4n** [comment] 2024-01-31 05:49
It sounds good to me @brooksmtownsend  
If the issue is valid and vacant then I'll definitely like to try my hands on it :) , thanks !

**Comment by UtkarshUmre** [comment] 2024-01-31 09:53
Hey @brooksmtownsend thanks for your help! I'll definitely work on this issue now. Since it seems like a good first problem, I'm looking forward to resolving it, So, what I understand as a beginner is that when we launch the wasmCloud environment with `wash up` it also accepts a couple of NATS parameters, right? Under the hood, wasmCloud takes these parameters and rewrites them in the `~/.wash` file. Also, can you please tell me from where wasmCloud obtains these parameters? According to my understanding, we don't have to supply different configuration flags; we can just provide `--nats-config ./myconfig` and `wash` will use that configuration for NATS instead. Some questions arise in my mind: first of all, how can I do this? Is there a specific resource from where I can learn to do this?

**Comment by connorsmith256** [comment] 2024-01-31 17:19
Hey @UtkarshUmre, I think a good starting place/example to work from is how wash handles the [nats_credsfile](https://github.com/wasmCloud/wasmCloud/blob/main/crates/wash-cli/src/up/mod.rs#L71) argument. What we're looking for is a new argument passed as `--nats-config-file` that is handled in a similar way.

If this argument is passed, rather than constructing a [NatsConfig](https://github.com/wasmCloud/wasmCloud/blob/main/crates/wash-cli/src/up/mod.rs#L369) struct from the other options and writing it out to disk, we should use the provided file.

You can see how the file is written to disk [here](https://github.com/wasmCloud/wasmCloud/blob/5925c6e196d8785d34f647002fcbe7b6252ac0aa/crates/wash-lib/src/start/nats.rs#L278)

**Comment by thomastaylor312** [comment] 2024-04-02 17:49
@UtkarshUmre are you still working on this or should we free it back up for others to work on?

**Comment by brooksmtownsend** [comment] 2024-06-07 15:00
Sounds great @Aditya1404Sal ! Since it would go stale, I'll assign you to it 😄

**Closed** 2024-06-29 02:38 UTC
Labels: enhancement, good first issue, help wanted, wash-cli
