### ISSUE TITLE
[BUG] wasmcloud-actor-extras 0.1.2 doesn't work with current wasmcloud

### ISSUE THREAD

**Issue by jsoverson** [wasmCloud/wasmCloud#201] opened 2021-05-27 17:52 UTC
**Describe the bug**
The operations in `extras` expect a `GeneratorRequest` struct passed as the argument but the interface that actors use doesn't generate or expect one to be passed. 

Extras implementation: [actual](https://github.com/wasmCloud/wasmCloud/blob/main/crates/wasmcloud-host/src/capability/extras.rs#L42-L45) and the [operation handler](https://github.com/wasmCloud/wasmCloud/blob/main/crates/wasmcloud-host/src/capability/extras.rs#L124) that show the payload gets deserialized into a `GeneratorRequest`

Extras interface: [extras/rust/generated/rs#L42-49]](https://github.com/wasmCloud/actor-interfaces/blob/885b23d2a060473e6e4ca416b1bde2d7a9de7dba/extras/rust/src/generated.rs#L42-L49) that shows a `GeneratorRequest` isn't set or expected

Extras schema: [extras.widl#L7](https://github.com/wasmCloud/actor-interfaces/blob/885b23d2a060473e6e4ca416b1bde2d7a9de7dba/extras/extras.widl#L7)

**To Reproduce**

1. Depend on `wasmcloud-actor-extras = { version = "0.1.2", features = ["guest"] }`
2. Add this to any actor `let guid = wasmcloud_actor_extras::default().request_guid()?;`

**Expected behavior**

Get a guid back

**Actual behavior**

Actor fails with a deserialization error on the host side.

**Environment (please complete the following information) **
- OS: Linux
- Architecture: x86_64
- Shell: zsh
- wasmcloud version: 0.18.2

**Comment by autodidaddict** [comment] 2021-05-27 18:04
FYI @brooksmtownsend

**Comment by autodidaddict** [comment] 2021-05-27 18:18
the provider implementation that's sitting inside wasmcloud 0.18 right now is the definitive, accurate version of that provider. So if the actor interface is out of sync with that, then the actor interface is what needs to change (IMHO).

**Comment by brooksmtownsend** [comment] 2021-06-01 13:34
This appears to be a duplicate of https://github.com/wasmCloud/wasmCloud/issues/175. I've opened up https://github.com/wasmCloud/actor-interfaces/issues/83 to track the issue for the interface, but I'm going to close this in favor of the previously opened issue. That issue will be where we can track when this is resolved (I'll work on this today).

**Closed by brooksmtownsend** 2021-06-01 13:34 UTC
Labels: bug, help wanted
