### ISSUE TITLE
[BUG] Ensure bad components do not affect the host

### ISSUE THREAD

**Issue by vados-cosmonic** [wasmCloud/wasmCloud#1949] opened 2024-04-18 15:12 UTC
### Affected project(s)

- [ ] documentation
- [ ] examples
- [X] wasmCloud host
- [ ] wasmCloud CLI (wash)
- [ ] wasmCloud dashboard UI (washboard)
- [ ] capability providers
- [ ] provider bindgen
- [ ] control interface client
- [ ] other / not sure

### Describe the bug

If a component handles streams incorrectly (in particular), it is possible for the host to hang and not exit properly, and for the host to report that the component is *missing*, despite it being listed in inventory.

Version 0.1.0 of `component-http-jsonify` has this problem -- *sometimes* it works just fine, and others 

### Steps to reproduce

1. Start the host (`wash up`)
2. Start a component with faulty stream handling (`wash start ghcr.io/component-http-jsonify:0.1.0 http-jsonify`)
3. Use `wash call` on the component (`wash call http-jsonify "wrpc:http/incoming-handler.handle"`)
4. Notice that the call fails, reporting that the component is missing, and the host then does not exit cleanly with Ctrl+C

### Expected behavior

The host should always be isolated from bad components

### Environment

- OS: Linux
- Shell ZSH
- wasmcloud Version 1.0.0

**Comment by brooksmtownsend** [comment] 2024-04-19 14:43
When we solve this issue, I definitely want to clarify here exactly the blast radius that we can reproduce. A hanging shutdown is more acceptable (IMO) than a component affecting another running component

**Comment by brooksmtownsend** [comment] 2024-04-30 16:27
This is primarily resolved by #2000 and #2017

**Comment by brooksmtownsend** [comment] 2024-05-08 19:48
Closing because of ☝🏻

**Closed by brooksmtownsend** 2024-05-08 19:48 UTC
Labels: bug, host, ux
