### ISSUE TITLE
Ensure automated tests are part of GH actions

### ISSUE THREAD

**Issue by stevelr** [wasmCloud/wasmCloud#245] opened 2021-08-30 21:42 UTC
This is an org-wide issue affecting several repositories. 
Github actions need to be reviewed and tested. Automated tests should be updated to test on all supported platforms. We should also consolidate some of the actions so they can be shared between repos and reduce code duplication

- [x] capability-providers (action for each provider)
- [ ] control-interface
- [x] examples (each example)
- [ ] interfaces (each interface, and integration tests)
- [ ] project-templates (gen project for each template with wash, build, and run sanity checks)
- [ ] wash
- [ ] wasmcloud.com-dev (check for doc builds, bad links, and spelling)
- [ ] wasmcloud-dev-site (check for doc builds, bad links, and spelling)
- [ ] wasmcloud-js
- [ ] wasmcloud-otp
- [ ] wasmcloud-test
- [ ] weld

**Comment by stevelr** [comment] 2021-08-31 15:59
we need to find ways to share code - common scripts, docker images, and/or custom github actions.

Also for more rapid iterations developing these, we might want to look into [act](https://github.com/nektos/act)

**Comment by brooksmtownsend** [comment] 2021-09-07 19:00
Because of #246 , some of this is duplicated. I suggest the following checklist:
- [ ] examples (any tests needed)
- [ ] interfaces (integration tests)
- [ ] project-templates (gen project for each template with wash, build, and run sanity checks)
- [ ] wasmcloud.com-dev (check for doc builds, bad links, and spelling)
- [ ] wasmcloud-dev-site (check for doc builds, bad links, and spelling)
- [ ] wasmcloud-js (integration tests)
- [ ] wasmcloud-otp (touching up integration tests, inline documentation comments)

**Comment by brooksmtownsend** [comment] 2021-09-15 16:56
@stevelr just checking, is the intent here just a duplicate of #246?

**Comment by stevelr** [comment] 2021-09-15 18:09
In #246, I had meant "publish release distributables" to mean anything that pushes to crates.io or docker or a azurecr.
This issue could be read to encompass #246.

**Closed** 2021-12-16 22:04 UTC
