### ISSUE TITLE
WasmCloud drops several requests 

### ISSUE THREAD

**Issue by f0rodo** [wasmCloud/wasmCloud#267] opened 2022-11-26 22:13 UTC
I recently tested WasmCloud  Hello Actor with siege and seeing quite a few dropped connections:

```
Transactions:                 596065 hits
Availability:                  99.98 %
Elapsed time:                4238.51 secs
Data transferred:               6.25 MB
Response time:                  0.12 secs
Transaction rate:             140.63 trans/sec
Throughput:                     0.00 MB/sec
Concurrency:                   16.57
Successful transactions:      596065
Failed transactions:             134 <-----
Longest transaction:          952.13
Shortest transaction:           0.00
```

Wash version 0.13.0

I am running this example: https://wasmcloud.dev/app-dev/create-actor/run/

I am running on

<img width="255" alt="image" src="https://user-images.githubusercontent.com/56056337/204110837-415f5730-cf21-4950-b0e0-657950aefe92.png">

**Comment by brooksmtownsend** [comment] 2022-11-28 14:37
Hey @f0rodo, thanks for putting in this issue. Could you link to the siege project so one of us can try and reproduce? I've got a similar-spec'd machine to yours (albeit with less memory) and would like to see what's causing the failed transactions.

Additionally, are you running a single instance of the hello module or multiple? It's worth noting that WebAssembly can only handle a single request at a time (no concurrency) but scheduling additional instances allows them to handle requests in parallel. Since you're running requests at a concurrency of `16.57` the requests might just get backed up

**Comment by f0rodo** [comment] 2022-11-29 22:05
Sure I ran 
`seige -c 100 http://localhost:8076?name=f0rodo"`
I had 100 instances running.

**Comment by brooksmtownsend** [comment] 2022-11-30 15:45
@f0rodo Where can one of us install `seige`?

**Comment by brooksmtownsend** [comment] 2023-03-11 01:24
@f0rodo I'm gonna go ahead and close this issue, please feel free to re-open if you're still hitting this bug and can give us a little more information about your testing strategy

**Closed by brooksmtownsend** 2023-03-11 01:24 UTC
