### ISSUE TITLE
Implement invocation verification

### ISSUE THREAD

**Issue by brooksmtownsend** [wasmCloud/wasmCloud#483] opened 2023-08-15 22:18 UTC
Invocations should be verified before they are handled, namely (checkboxes for #528)
- [x] The cluster issuer of the invocation should be in the host's cluster issuer list
- [x] The hash of the invocation should match
- [x] Actors initiating an invocation should have the proper capability claim to make that invocation
- [x] Actors receiving an invocation should have the proper capability claim to receive that invocation

In addition to the above requirements, we should reach out to a policy server as well, which will be handled separately with #480

**Comment by rvolosatovs** [comment] 2023-08-16 12:06
Isn't this a duplicate of https://github.com/wasmCloud/wasmCloud/issues/447 ?

**Comment by brooksmtownsend** [comment] 2023-08-16 18:06
> Isn't this a duplicate of #447 ?

Not quite, will add more detail to specify

**Closed** 2023-08-25 14:42 UTC
