### ISSUE TITLE
Following Getting Started Instructions Gives Me Error

### ISSUE THREAD

**Issue by bluesunrise** [wasmCloud/wasmCloud#275] opened 2023-03-10 21:28 UTC
Following instructions here:

https://wasmcloud.com/docs/getting-started

I started the server with 

`wash up`

and then opened a new shell, set the WASMCLOUD_CLUSTER_SEED env.var, and typed:

`wash ctl get hosts`

Error:

Failed to create NATS client

Caused by:
    0: Failed to connect to NATS 127.0.0.1:4222
       No credentials file was provided, you may need one to connect.
    1: failed to read root certificates: MissingOrMalformedExtensions

**Comment by thomastaylor312** [comment] 2023-03-10 23:23
@bluesunrise Can you try without setting a cluster seed at all? Might want to run `rm -f ~/.wash/host_config.json` before you do that just to be safe as well

**Comment by bluesunrise** [comment] 2023-03-11 00:32
@thomastaylor312  I've tried several variations of resetting cluster seed, removing host_config.json, no success

**Comment by bluesunrise** [comment] 2023-03-11 00:34
NOTE: using a Mac and I installed with Homebrew

```
brew tap wasmcloud/wasmcloud
brew install wash
```

**Comment by pgray** [comment] 2023-03-11 00:56
heya, @bluesunrise,
thanks for filing an issue.
Can you paste the output from running the commands below?
(assuming `wash up` is running):
```
uname -p
wash --version
echo $(bash -c "$HOME/.wash/downloads/nats-server --version")
nc -zv4 localhost 4222
```

**Comment by bluesunrise** [comment] 2023-03-11 01:17
i386
wash 0.15.1
nats-server: v2.9.14
Connection to localhost port 4222 [tcp/*] succeeded!

**Comment by pgray** [comment] 2023-03-11 02:05
Interesting, I wonder what happens for something like this:
```
git clone https://github.com/nats-io/nats.rs \
&& cd nats.rs/async-nats \
&& cargo run --example kv```
That's the client library we use to connect to `nats`

**Comment by pgray** [comment] 2023-03-11 02:10
also this might disable TLS if it's trying that by default:
```
wash ctl get hosts --ctl-host nats://127.0.0.1
```

**Comment by bluesunrise** [comment] 2023-03-11 02:20
The `--ctl-host` option didn't help, same error. Here is the output of the command above:

```
....
   Running `/Users/dtaylor/spin/wcloud/nats.rs/target/debug/examples/kv`
sue.color @ 1 -> blue
sue.color @ 2 -> green
sue.color @ 3 -> red
All keys: ["sue.color"]
KV stream name: OBJ_default
$KV.profiles.sue.color @ 3 -> red
$KV.profiles.sue.color @ 4 -> yellow
$KV.profiles.sue.color @ 5 ->
headers: HeaderMap { inner: {HeaderName { value: "KV-Operation" }: HeaderValue { value: ["DEL"] }} }
sue.color @ 6 -> purple (op: Put)
sue.food @ 7 -> pizza (op: Put)
```

**Comment by connorsmith256** [comment] 2023-03-14 18:45
Hey @bluesunrise, were you able to try `wash ctl get hosts --ctl-host nats://127.0.0.1` ? I'm curious if the NATS lib might be defaulting to TLS on your system for some reason, and whether specifying `nats://` works around that

**Comment by bluesunrise** [comment] 2023-03-14 23:17
Hi @connorsmith256, The --ctl-host option didn't help, same error.

 wash ctl get hosts --ctl-host nats://127.0.0.1

Failed to create NATS client

Caused by:
    0: Failed to connect to NATS nats://127.0.0.1:4222
       No credentials file was provided, you may need one to connect.
    1: failed to read root certificates: MissingOrMalformedExtensions

**Comment by connorsmith256** [comment] 2023-03-14 23:27
Thanks for the extra info. I poked around a bit in the NATS source and discovered [this snippet](https://github.com/nats-io/nats.rs/blob/510369c1bb3f3814ab53d16af984c22b65e32ce1/async-nats/src/tls.rs#L78)

Do you have root certs installed on your system?

**Comment by bluesunrise** [comment] 2023-03-14 23:35
> Do you have root certs installed on your system?
I don't think so. I moved my .ssh directory and retested, still the same problem
I have used NATS quite a bit on another project on this machine, but I usually ran it in a container

**Comment by connorsmith256** [comment] 2023-03-15 20:52
Hmm. I think this might be worked around in https://github.com/nats-io/nats.rs/releases/tag/async-nats%2Fv0.26.0 (by not trying to load certs at all), but we're not ready to upgrade in wash yet

The error is coming from a dependency of a dependency (`rustls`) and it's related to parsing SSL certs on your system. The actual error is from [even deeper](/Users/connor/.cargo/registry/src/github.com-1ecc6299db9ec823/webpki-0.22.0/src/error.rs) in the dependency chain:

```
    /// The certificate extensions are missing or malformed.
    ///
    /// In particular, webpki requires the DNS name(s) be in the subjectAltName
    /// extension as required by the CA/Browser Forum Baseline Requirements
    /// and as recommended by RFC6125.
```

Since you're using the same (default) settings many of us are, I suspect there's _something_ different about your system related to TLS, but I'm not sure what that would be, and I recognize "it works on our machines" isn't a satisfying answer 🙁 

My only suggestion would be to try on another machine, see if you can reproduce there, and let us know.

**Comment by autodidaddict** [comment] 2023-05-01 12:33
Just checking in to see if this is still an open issue?

**Comment by bluesunrise** [comment] 2023-05-01 20:10
Unfortunately I gave up

**Comment by brooksmtownsend** [comment] 2023-05-10 16:16
Closing since this seems to have reached a dead end, this seems like a missing set of ca-certificates which should be resolved with
```
brew install openssl@1.1
```

**Closed by brooksmtownsend** 2023-05-10 16:16 UTC

**Comment by bluesunrise** [comment] 2023-05-11 22:47
I just uninstalled wash, reinstalled, and the problem went away! (its been two months since I last tried)

"Congratulations on installing wash!  Shell auto-complete is available. For instructions on setting up auto-complete for your shell, please see 'https://github.com/wasmCloud/wash/blob/main/Completions.md'"

Thanks!
