### ISSUE TITLE
Introduce shared capability claim checking utilities

### ISSUE THREAD

**Issue by rvolosatovs** [wasmCloud/wasmCloud#290] opened 2023-03-16 19:21 UTC
In https://github.com/wasmCloud/wasmCloud/pull/289 capability claim checking was removed due to the fact that in general case, the host does not have enough context to perform that check. It would be great to introduce some sharing capability checking functionality to this crate

**Comment by brooksmtownsend** [comment] 2023-03-17 13:32
Particularly, to add a little more detail, this crate has enough information to check the target of the invocation is allowed based on the capability claims of the actor making the request, but only that much. For example we can, today, deny an actor from invoking a capability that it doesn't have the proper claims for. We can also early return if the target is an actor public key to allow an actor call.

The only scenario (that I know of) that we can't account for is invoking via call alias. Since call aliases are claims that are present in the lattice and not in this crate we can't check it.

I think one way we could enforce this is by having actors declare the call aliases they wish to use in their capability claims, then we would have enough context. It feels a little clunky, since we wouldn't in turn require you to declare actor IDs (unless we wanted to) but it would lead to a nice level of visibility into everything an actor may try to call external. Thoughts @autodidaddict ?

**Comment by autodidaddict** [comment] 2023-03-17 13:40
The correct issue is it can't tell the difference between a call alias and contract id so it can't reliably determine whether the target of an invocation requires a claims check.

**Comment by autodidaddict** [comment] 2023-03-17 13:41
The correct issue is it can't tell the difference between a call alias and contract id so it can't reliably determine whether the target of an invocation requires a claims check.

Embedding the call aliases needed in claims actually prevents the number one use case for call aliases: determining which actor to call at runtime

**Comment by autodidaddict** [comment] 2023-03-17 14:02
> > Embedding the call aliases needed in claims actually prevents the number one use case for call aliases: determining which actor to call at runtime
> 
> Well, you have to compile that call alias in anyways, the only thing that changes is the public key behind the call alias. But if you just signed your actor with the call alias, e.g.
> ```
> wash claims sign pinger.wasm -c wasmcloud:httpserver -c wasmcloud/ponger
> ```
> 
> Essentially just declaring what you've already hardcoded as a constant

Actually the call alias isn't compiled. The same way you can choose a link name at runtime you need to be able to choose a call alias at runtime. There are a couple of scenarios that require this.

**Comment by brooksmtownsend** [comment] 2023-08-23 18:45
Duplicate of #483

**Closed by brooksmtownsend** 2023-08-23 18:45 UTC
